"use client";

import { useState } from "react";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { PageHero } from "@/components/ui/PageHero";

type Article = { title: string; text: string };

const articles: Article[] = [
  {
    title: "The Triune God",
    text: "We believe in one God, eternally existing in three Persons: the Father, the Son and the Holy Spirit.",
  },
  {
    title: "Jesus Christ",
    text: "We believe that Jesus Christ was begotten of the Father, conceived by the Holy Spirit, born of the Virgin Mary, and is true God and true man.",
  },
  {
    title: "Man and Sin",
    text: "We believe that God created man in His own image; that man sinned and thereby incurred the penalty of sin, which is death physically and spiritually; and that all human beings inherit a sinful nature which issues in actual transgression involving personal guilt.",
  },
  {
    title: "Sexual Behaviour",
    text: "With regard to sexual behaviour, we believe in heterosexual relationships between a natural man and a natural woman within the confines of lawful matrimony. Adherence to this principle of sexual behaviour is an inherent requirement of membership of Christian Family Church.",
  },
  {
    title: "The Atonement",
    text: "We believe that the Lord Jesus Christ died for our sins as a substitutionary sacrifice according to the Scriptures, and that all who believe in Him are justified on the grounds of His shed blood.",
  },
  {
    title: "Resurrection and Ascension",
    text: "We believe in the bodily resurrection of the Lord Jesus, His ascension into Heaven, and His present life there as our High Priest and Advocate.",
  },
  {
    title: "The Return of Christ",
    text: "We believe in the personal return of the Lord Jesus Christ.",
  },
  {
    title: "The New Birth",
    text: "We believe that all who repent of their sin and receive the Lord Jesus Christ by faith are born again of the Holy Spirit and thereby become children of God.",
  },
  {
    title: "The Holy Spirit",
    text: "We believe in the Baptism in the Holy Spirit, empowering and equipping believers for service with the accompanying supernatural gifts of the Holy Spirit, and in fellowship with the Holy Spirit. We believe in the divinely ordained ministries of the Apostle, Prophet, Teacher, Pastor and Evangelist.",
  },
  {
    title: "Submission to Authority",
    text: "With regard to submission to authority, we believe in the principle of being in authority because you are under authority. Christian Family Church membership is subject to submission to authority in matters of church governance, doctrine and personal behaviour.",
  },
  {
    title: "The Resurrection of the Dead",
    text: "We believe in the resurrection of both the just and the unjust, the eternal blessedness of the redeemed, and the eternal banishment of those who have rejected the offer of salvation.",
  },
  {
    title: "The Church",
    text: "We believe that the one true Church is the whole company of those redeemed by Jesus Christ and regenerated by the Holy Spirit, and that the new birth and personal confession of Christ are essentials of church membership.",
  },
  {
    title: "The Ordinances",
    text: "We believe that the Lord Jesus Christ appointed two ordinances: Baptism in water, and the Lord’s Supper, to be observed as acts of obedience and as perpetual witnesses to the central truths of the Christian faith.",
  },
  {
    title: "Divine Healing",
    text: "We believe that divine healing was provided for in the Old and New Testaments and is an integral part of the Gospel.",
  },
  {
    title: "Sanctification",
    text: "We believe that without holiness no one can see the Lord, and in the doctrine of sanctification as a definite yet progressive work of grace, commencing at the new birth and continuing until the consummation of salvation.",
  },
  {
    title: "The Great Commission",
    text: "We believe in obeying the commission of Jesus in Matthew 28:19-20, to go and make disciples of all nations, baptising them and teaching them to obey all that He commanded.",
  },
];

export default function StatementOfFaithPage() {
  const [open, setOpen] = useState<number>(0);

  return (
    <main style={{ width: "100%", overflowX: "hidden", color: "#11203F", background: "#fff" }}>
      <Nav active="about" overlay />

      <PageHero
        image="/assets/img-worship-band.jpg"
        eyebrow="What We Believe"
        title="Statement of Faith"
        minHeight="56vh"
        gradient="linear-gradient(to top, rgba(7,15,33,.92), rgba(7,15,33,.3) 70%)"
      />

      <section style={{ background: "#fff", padding: "clamp(64px,8vw,110px) clamp(20px,4vw,40px)" }}>
        <div style={{ maxWidth: 860, margin: "0 auto" }}>
          <p style={{ fontSize: 18, lineHeight: 1.7, color: "#3a4660", margin: "0 0 12px" }}>
            This is what we believe at Christian Family Church.
          </p>
          <p style={{ fontFamily: "var(--font-archivo)", fontWeight: 800, fontSize: "clamp(22px,2.8vw,30px)", lineHeight: 1.3, letterSpacing: "-.01em", color: "#11203F", margin: "0 0 48px" }}>
            We believe in the Scriptures of the Old and New Testaments, in their original writing, as fully inspired of God, and accept them as the supreme and final authority for faith and life.
          </p>

          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {articles.map((a, i) => {
              const isOpen = i === open;
              const no = String(i + 2).padStart(2, "0");
              return (
                <div key={a.title} style={{ borderBottom: "1px solid #e6e8ee" }}>
                  <button
                    onClick={() => setOpen((cur) => (cur === i ? -1 : i))}
                    aria-expanded={isOpen}
                    style={{
                      width: "100%",
                      display: "flex",
                      alignItems: "center",
                      gap: "clamp(16px,3vw,28px)",
                      background: "transparent",
                      border: "none",
                      cursor: "pointer",
                      padding: "24px 4px",
                      textAlign: "left",
                    }}
                  >
                    <span style={{ flexShrink: 0, fontFamily: "var(--font-archivo)", fontWeight: 900, fontSize: 18, color: "#cfd5e0", lineHeight: 1.5, minWidth: 30 }}>{no}</span>
                    <span style={{ flex: 1, fontFamily: "var(--font-archivo)", fontWeight: 700, fontSize: "clamp(17px,2vw,21px)", color: "#11203F" }}>{a.title}</span>
                    <span
                      style={{
                        flexShrink: 0,
                        width: 30,
                        height: 30,
                        borderRadius: "50%",
                        background: isOpen ? "#2E6BE6" : "#eef1f6",
                        color: isOpen ? "#fff" : "#11203F",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontSize: 20,
                        transition: "all .2s",
                      }}
                    >
                      {isOpen ? "−" : "+"}
                    </span>
                  </button>
                  <div style={{ display: "grid", gridTemplateRows: isOpen ? "1fr" : "0fr", transition: "grid-template-rows .35s ease" }}>
                    <div style={{ overflow: "hidden" }}>
                      <p style={{ fontSize: 16.5, lineHeight: 1.72, color: "#5A6478", margin: 0, padding: "0 4px 26px 62px" }}>{a.text}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <p style={{ fontSize: 16, lineHeight: 1.72, color: "#5A6478", fontStyle: "italic", margin: "40px 0 0", paddingTop: 30, borderTop: "2px solid #2E6BE6" }}>
            This fellowship is open to any further truth which the Holy Spirit may illuminate from the Scriptures.
          </p>
        </div>
      </section>

      <Footer />
    </main>
  );
}
